# Generated by Django 5.0.6 on 2024-07-05 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('family_name', models.CharField(max_length=20)),
                ('instruments', models.ManyToManyField(to='agenda.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('item_date', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='item date')),
                ('location', models.CharField(max_length=50)),
                ('lineUp', models.ManyToManyField(to='agenda.performer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='performer',
            constraint=models.UniqueConstraint(fields=('family_name', 'middle_name', 'family_name'), name='unique performer name'),
        ),
    ]
