"""
Django settings for dtap project.

Generated by 'djangocms' command using django CMS 4.1.1 and Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of Django settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

For the list of django CMS settings and their values, see
https://docs.django-cms.org/en/release-4.1.x/reference/configuration.html
"""

import os
from pathlib import Path

from .settingsB import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS=["dakterrasart.nl", "localhost", "127.0.0.1"]